package com.amazon.atlas22.competitive;

public class MaxProfits {

	/*
	 	
	 	BitCoin which is having below different prices
	 	
	 	Day1 21138
	 	Day2 21517
	 	Day3 21416
	 	Day4 21829
	 	Day5 21600
	 	Day6 21365
	 	Day7 21565
	 	
	 	Consider if we buy the Bitcoin on Day1 for => 21138
	 	And we Sell it on Day7 for 				   => 21565
	 	Profit =>								-  => 427		+ve => Profit	
	 	
	 	Consider if we buy the Bitcoin on Day4 for => 21829
	 	And we Sell it on Day6 for 				   => 21365
	 	Profit =>								-  => -464		-ve => Loss
	 	
	 	Find the Maximum Profit which can be generated by purchasing the BitCoin on a day and selling it some other day
	 */
	
	static int getMaxProfit(int[] prices) {
		
		int maxProfit = 0;
		
		
		return maxProfit;
		
	}
	
	public static void main(String[] args) {
	
		int[] bitCoinPriceWeekly = {21138, 21517, 21416, 21829, 21600, 21365, 21565};
		int maxProfit = getMaxProfit(bitCoinPriceWeekly);
		System.out.println("Max Profit is: "+maxProfit);
		
	}

}
